name: oatpp-boilerplate-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: oatpp-boilerplate-${{ github.ref_name }}-mingw.zip
    steps:
    - uses: actions/checkout@v2
    
    - name: Check cmake
      run: cmake --version
      
    - name: Download oatpp-v1.3.0-mingw.zip
      run: aria2c https://github.com/dirkarnez/oatpp-prebuilt/releases/download/v1.3.0/oatpp-v1.3.0-mingw.zip
      
    - name: Extract some files
      run: 7z x oatpp-v1.3.0-mingw.zip
      
    - name: Make build directory
      run: md build        
         
    - name: Configure
      shell: cmd
      run: cmake -S. -Bbuild -G "MinGW Makefiles" -DOATPP_ROOT="%cd%/oatpp-v1.3.0-mingw/lib/cmake/oatpp-1.3.0"

    - name: Build
      run: cd build && mingw32-make.exe
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        directory: "build"
        filename: "${{ env.mingwTargetZip }}"

    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/${{ env.mingwTargetZip }}"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
